name: Auto Sync bekonon Bot
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

      - name: Verify Changes
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then
            echo "Uncommitted changes detected, committing..."
            git add .
            git commit -m "Auto-sync bot file changes"
            git push origin main
          else
            echo "No uncommitted changes detected"
          fi